server:
  port: 8085
  servlet:
    context-path: /api/v1

spring:
  application:
    name: careflow-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/careflow_db}
    username: ${SPRING_DATASOURCE_USERNAME:careflow_user}
    password: ${SPRING_DATASOURCE_PASSWORD:careflow_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: careflowSuperSecretKeyForDevelopmentPhaseProductionReady2026!
  expiration-ms: 86400000

careflow:
  i18n:
    default-locale: en
    supported-locales: en,hi,ta,te,kn,mr,bn
